-- Sprzedaż ogólna
CREATE VIEW sprzedaz_ogolna AS
SELECT
    COUNT(DISTINCT ZAMOWIENIE_ID) AS liczba_zamowien,
    SUM(WARTOSC) AS wartosc_sprzedazy
FROM
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA;

-- Sprzedaż według branż
CREATE VIEW sprzedaz_branze AS
SELECT
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.BRANZE.BRANZA_NAZWA,
    COUNT(DISTINCT PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.ZAMOWIENIE_ID) AS liczba_zamowien,
    SUM(PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.WARTOSC) AS wartosc_sprzedazy
FROM
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.KLIENCI
    JOIN PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA ON PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.KLIENCI.KLIENT_ID = PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.KLIENT_ID
    JOIN PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.BRANZE ON PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.KLIENCI.BRANZA_ID = PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.BRANZE.BRANZA_ID
GROUP BY
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.BRANZE.BRANZA_NAZWA;

-- Sprzedaż według sektorów
CREATE VIEW sprzedaz_sektory AS
SELECT
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.SEKTORY.SEKTOR_NAZWA,
    COUNT(DISTINCT PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.ZAMOWIENIE_ID) AS liczba_zamowien,
    SUM(PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.WARTOSC) AS wartosc_sprzedazy
FROM
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.KLIENCI
    JOIN PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA ON PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.KLIENCI.KLIENT_ID = PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.KLIENT_ID
    JOIN PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.SEKTORY ON PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.KLIENCI.SEKTOR_ID = PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.SEKTORY.SEKTOR_ID
GROUP BY
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.SEKTORY.SEKTOR_NAZWA;

-- Sprzedaż według przedstawicieli
CREATE VIEW sprzedaz_przedstawiciele AS
SELECT
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.PRZEDSTAWICIEL.KAM_NAZWA,
    COUNT(DISTINCT PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.ZAMOWIENIE_ID) AS liczba_zamowien,
    SUM(PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.WARTOSC) AS wartosc_sprzedazy
FROM
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.KLIENCI
    JOIN PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA ON PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.KLIENCI.KLIENT_ID = PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.KLIENT_ID
    JOIN PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.PRZEDSTAWICIEL ON PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.KLIENCI.KAM_ID = PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.PRZEDSTAWICIEL.KAM_ID
GROUP BY
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.PRZEDSTAWICIEL.KAM_NAZWA;

-- Sprzedaż według towarów
CREATE VIEW sprzedaz_towary AS
SELECT
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.TOWARY.GRUPA_NAZWA,
    COUNT(DISTINCT PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.ZAMOWIENIE_ID) AS liczba_zamowien,
    SUM(PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.WARTOSC) AS wartosc_sprzedazy
FROM
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA
    JOIN PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.TOWARY ON PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.ZAMOWIENIA.TOWAR_ID = PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.TOWARY.TOWAR_ID
GROUP BY
    PIEKUTOWSKA.PIEKUTOWSKASPRZEDAZ.TOWARY.GRUPA_NAZWA; 